# Generated by Django 3.0 on 2019-12-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='update',
            new_name='updated',
        ),
    ]
