# Generated by Django 3.0 on 2019-12-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191226_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='masterbdx', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lat_name',
            field=models.CharField(default='bd', max_length=255),
            preserve_default=False,
        ),
    ]
