# Generated by Django 3.0 on 2019-12-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191227_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lat_name',
            new_name='last_name',
        ),
    ]
