# Generated by Django 3.0 on 2019-12-30 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191230_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follwing',
            field=models.ManyToManyField(blank=True, related_name='follwed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
