# Generated by Django 3.0 on 2020-01-01 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191230_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follwing',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
