# Generated by Django 3.2.5 on 2021-07-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.EmailField(default='2180945373551', max_length=255, unique=True, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
