# Generated by Django 3.2.5 on 2021-07-14 16:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=255, region=None, unique=True, verbose_name='Phone Number'),
        ),
    ]
